
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/Content_center
    hikari:
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.28.2:9876
        bindings:
          output:
            producer:
              #表明是事务消息
              transactional: true
              group: tx-add-bonus-group
      bindings:
        output:
          #用来指定topic
          #destination: stream-test-topic
          destination: add-bonus
        my-output:
          destination: stream-my-topic
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
        metadata:
          #自己这个实例的版本
          version: v1
          #允许调用的提供者版本
          target-version: v1
        #命名空间，具有隔离性
        #namespace: 55fb8bc1-faaf-463f-9b02-c7d9099f48e9
    #设置sentinel的控制台
    sentinel:
      transport:
        dashboard: localhost:8844
        client-ip: 10.10.254.37
      #开启/关闭对spring mvc断点的保护
      filter:
        enabled: true
server:
  port: 8811


user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.imooc.contentcenter.config.NacosFinalRule

#饥饿加载，解决第一次加载过慢的问题
#ribbon:
#  eager-load:
#    enabled: true
#    clients: user-center

ribbon:
  eager-load:
    enabled: true
    clients: user-center
#开启Feign日志打印
logging:
  level:
    com.alibaba.nacos: error
    com.imooc.contentcenter.feignclient.UserCenterFeignClient: debug
#配置文件配置
#feign:
#  client:
#    config:
#      user-center:
#        loggerLevel: full
#全局配置Feign日志打印
feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      default:
        loggerLevel: full
        requestInterceptors:
          - com.imooc.contentcenter.feignclient.interceptor.TokenRelayRequestInterceptor
  httpclient:
    #让feign使用apache httpclient做请求；而不是默认的urlconnect
    enabled: true
    #feign的最大连接数
    max-connections: 200
    #feign单个路径的最大连接数
    max-connections-per-route: 50
#  okhttp:
#    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#resttemplate:
#  sentinel:
#    #关闭@SentinelRestTemplate注解
#    enabled: false
rocketmq:
  name-server: 192.168.28.2:9876
  producer:
    #小坑：必须制定group
    group: test-group
mybatis:
  mapper-locations: classpath:/mapper/*.xml