server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
        # 让gateway通过服务发现组件找到其他的微服务
         enabled: true
         # lower-case-service-id: true
      routes:
        - id: user-center
          uri: lb://user-center
          predicates:
            - Path=/user-center/**
          filters:
            - StripPrefix=1
        - id: content-center
          uri: lb://content-center
          predicates:
            - Path=/content/**
          filters:
            - StripPrefix=1
#        - id: after_route
#          uri: lb://user-center
#          predicates:
#            # 当且仅当请求时的时间After配置的时间时，才会转发到用户微服务
#            # 目前配置不会进该路由配置，所以返回404
#            # 将时间改成 < now的时间，则访问localhost:8040/** -> user-center/**
#            # eg. 访问http://localhost:8040/users/1 -> user-center/users/1
#            #- After=2030-01-20T17:42:47.789-07:00[America/Denver]
#            #自定义谓词工厂
#            - TimeBetween=上午9:00, 下五5:00
#            - filters:
#                #内置过滤器添加请求头参数
#                - AddRequestHeader=X-Request-Foo, Bar
#                - PreLog=a,b
  zipkin:
    base-url: http://localhost:9411/
    #discovery-client-enabled: false
    discoveryClientEnabled: false
  sleuth:
    sampler:
      #抽样率，默认是0.1
      probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always